# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

  # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
  export PATH="$PATH:$HOME/.rvm/bin"

  alias 'zalora'='cd ~/Documents/zalora'
  alias 'sandbox'='cd ~/Documents/sandbox'
  alias 'pets'='cd ~/Documents/petProjects'
  alias 'md'='open -a /Applications/MacDown.app'
  alias 'st'='open -a /Applications/SourceTree.app'
  alias 'gif'='givegif'
  alias 'rn'='react-native'

  function f_notifyme {
  LAST_EXIT_CODE=$?
  CMD=$(fc -ln -1)
  # No point in waiting for the command to complete
  notifyme "$cmd" "$last_exit_code" &
}

export ps1='$(f_notifyme)'$ps1}

plugins=(zsh-autosuggestions)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="#333"

# https://superuser.com/questions/292652/change-iterm2-window-and-tab-titles-in-zsh/292660#292660
DISABLE_AUTO_TITLE="true"
alias config='/usr/bin/git --git-dir=/Users/khoangtrieu/.cfg/ --work-tree=/Users/khoangtrieu'
alias config='/usr/bin/git --git-dir=/Users/khoangtrieu/.cfg/ --work-tree=/Users/khoangtrieu'
