#!/usr/local/bin/python3
import subprocess

# bring kitty to front
app_name = "kitty"
script = f'tell application "System Events" to set frontmost of process "{app_name}" to true'
subprocess.run(['osascript', '-e', script])
