require('general/settings')

require('plugins')
require('plugins/vifm')
require('plugins/symbols-outline')
require('plugins/fzf')
require('plugins/compe')
require('plugins/autopairs')
require('plugins/gitgutter')
require('plugins/easymotion')
require('plugins/ale')
require('plugins/fugitive')
require('plugins/treesitter')
require('plugins/lsp')
require('plugins/indent-blankline')
require('plugins/colorizer')
require('plugins/gitlinker')
require('plugins/telescope')
require('plugins/vimspector')
require('plugins/harpoon')
require('plugins/find_dotfiles')
require('plugins/lightline')

require('colorschemes/lua/oceannext')
require('general/mappings')
